### PR TITLE
Update ruby-build version to v20230330

### PR DESCRIPTION
**Pull request by landonepps**
We need to update the ruby-build version in order to support Ruby 3.2.2.

Without this change, you get an error trying to install Ruby 3.2.2:
```
❯ rtx install ruby
Version not found
Version not found
rtx ruby@3.2.2 installing
rtx failed to install ruby@3.2.2
```

### CODE REVIEW

**Comment by sphinxc0re** [comment]
Any updates on this? A vendor I'm working with uses 3.2.2 and I don't want to use any other version manager 🙏🏼

**Comment by chadlwilson** [comment]
Hello @jdxcode - any thoughts on how to move this forward?

Maybe worth thinking about adding automation to pull from upstream the new ruby-build versions which unfortunately require code change right now. Until something like https://github.com/asdf-vm/asdf-ruby/pull/320 is merged upstream.

For those who aren't aware, workaround is like the below
`RTX_RUBY_BUILD_VERSION=master rtx install ruby@3.1.4`
`RTX_RUBY_BUILD_VERSION=master rtx install ruby@3.2.2`

**Comment by jdx** [comment]
sorry I wasn't watching this repo so missed the original PR

**Comment by chadlwilson** [comment]
Thanks! 🙏

**Pull request closed without merging**
